### ISSUE TITLE
What is the idea behind supporting tsx?

### ISSUE THREAD

**Issue by warmthsea** [vuejs/repl#241] opened 2024-04-24 03:12 UTC
https://github.com/vuejs/repl/blob/331588acdbd01496f9a79102b1a16b08834b7e1a/src/transform.ts#L80

**Comment by sxzz** [comment] 2024-05-23 14:51
This project does not support plugins (such as Rollup plugins), so if we need this feature, it should be supported natively.

**Comment by sxzz** [comment] 2024-05-23 15:02
Duplicate of #57

**Closed by sxzz** 2024-05-23 15:02 UTC
