### ISSUE TITLE
在组件中正确引入cesium 可以渲染但是没有出现预期中的地球

### ISSUE THREAD

**Issue by JensonMiao** [vuejs/repl#187] opened 2023-12-14 11:21 UTC
效果截图：![image](https://github.com/vuejs/repl/assets/46488783/252fde1a-c887-47e6-a48f-212ff9e6f658)
实际应该出现地球：
![image](https://github.com/vuejs/repl/assets/46488783/6fdc6ff6-d22f-4ff2-aa9b-6b33e0cd417c)

**Comment by sxzz** [comment] 2023-12-14 15:53
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by sxzz** 2023-12-14 15:53 UTC
