### ISSUE TITLE
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html"

### ISSUE THREAD

**Issue by alvin0804** [vuejs/repl#235] opened 2024-03-28 14:30 UTC
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

visit the http://localhost:5173/node_modules/.vite/assets/vue.worker-g2_gKJKV.js file has some error in chrome console

<img width="1433" alt="image" src="https://github.com/vuejs/repl/assets/103974234/13bd7325-dbb0-48e0-bb0a-0d5ff8fb5fd8">

@vue/repl version: 4..1.1

**Comment by marcoarruda** [comment] 2024-04-24 18:10
I had the same issue, any news on that?

**Comment by sxzz** [comment] 2024-05-23 14:45
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by alvin0804** [comment] 2024-05-23 14:46
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Closed by sxzz** 2024-05-23 14:45 UTC

**Comment by wolmir-truelogic** [comment] 2024-12-06 12:26
You need to add this to your vite config:
`optimizeDeps: {
    exclude: ['@vue/repl'],
  },`
