### ISSUE TITLE
error in vue-cli4 project currently no loaders are configured to process this file

### ISSUE THREAD

**Issue by wangpf110** [vuejs/repl#76] opened 2023-03-09 10:00 UTC
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/12610890/223987347-8c68f018-664a-4b5d-952f-404fffa5e734.png">
please help me , how to config repl loader?

**Comment by sxzz** [comment] 2023-03-09 12:28
https://danw1ld.medium.com/optional-chaining-for-javascript-with-babel-7-and-webpack-4-2de8fd9dbdd5

**Comment by wangpf110** [comment] 2023-03-10 02:57
this is error in node_modules
` error  in ./node_modules/@vue/repl/dist/vue-repl.js`
I add `babel-loader` to `repl` in `vue.config.js`
`configureWebpack: {
    module: {
      rules: [
        {
          test: /repl[\\/].*\.js$/,
          loader: 'babel-loader',
        },
      ],
    },
  },`

**but another error**  
These dependencies were not found:

* atpl in ./node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js
* babel-core in ./node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js
* bracket-template in ./node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js
* coffee-script in ./node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js
* dot in ./node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js
* dustjs-linkedin in ./node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js
* eco in ./node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js
* ect in ./node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js
* haml-coffee in ./node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js
* hamlet in ./node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js
* hamljs in ./node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js
* handlebars in ./node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js
* hogan.js in ./node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js
* htmling in ./node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js
* jazz in ./node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js
* jqtpl in ./node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js
* just in ./node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js
* liquor in ./node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js
* marko in ./node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js
* mote in ./node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js
* mustache in ./node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js
* plates in ./node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js
* ractive in ./node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js
* react in ./node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js
* react-dom/server in ./node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js
* slm in ./node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js
* squirrelly in ./node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js
* teacup/lib/express in ./node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js
* templayed in ./node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js
* toffee in ./node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js
* twig in ./node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js
* twing in ./node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js
* underscore in ./node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js
* vash in ./node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js
* velocityjs in ./node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js
* walrus in ./node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js
* whiskers in ./node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js

To install them, you can run: npm install --save atpl babel-core bracket-template coffee-script dot dustjs-linkedin eco ect haml-coffee hamlet hamljs handlebars hogan.js htmling jazz jqtpl just liquor marko mote mustache plates ractive react react-dom/server slm squirrelly teacup/lib/express templayed toffee twig twing underscore vash velocityjs walrus whiskers

**Comment by minghua233** [comment] 2023-03-13 07:11
I have the same problem
<img width="686" alt="image" src="https://user-images.githubusercontent.com/70757237/224631585-b3574256-2f9c-47b0-b6f9-5557a17f674c.png">

**Comment by sxzz** [comment] 2023-06-23 13:04
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

https://antfu.me/posts/why-reproductions-are-required

**Closed by sxzz** 2023-06-23 13:04 UTC
