### ISSUE TITLE
store.setImportMap doesn't work in VitePress

### ISSUE THREAD

**Issue by YangTingTing-tech** [vuejs/repl#170] opened 2023-11-06 08:46 UTC
I use @vue/reply in vitepress to show my UI demo, but it doesn't work to setImportMap.
The wrong Message in iframe is "Failed to resolve module specifier "dayjs".
Tip: edit the "Import Map" tab to specify import paths for dependencies."
There already exist a imports about 'element-plus' in Import Map, like this:
![image](https://github.com/vuejs/repl/assets/132062560/167751d7-ec3d-4285-94ff-f225813f1a23)

Here is my code in a .vue file.

```
<script setup>
import { watchEffect, ref } from 'vue'
import { Repl, ReplStore } from '@vue/repl'
import Monaco from '@vue/repl/monaco-editor'
import '@vue/repl/style.css'

const query = new URLSearchParams(location.search)
const store = new ReplStore()

watchEffect(() => history.replaceState({}, '', store.serialize()))

store.setImportMap({
    imports: {
        'element-plus': 'https://unpkg.com/element-plus@2.2.5/es/index.mjs'
    }
})

const customImportStatements = ref([`import ElementPlus from 'element-plus'`])
const customAppUsageCodes = ref([`app.use(ElementPlus)`])
const customHeadTags = ref([
    `<link ref="stylesheet" href="https://unpkg.com/element-plus@2.2.5/dist/index.css">`
])
</script>

<template>
    <Repl :editor="Monaco" :store="store" :clearConsole="false" :previewOptions="{
        headHTML: customHeadTags,
        customCode: {
            importCode: customImportStatements,
            useCode: customAppUsageCodes,
        },
    }" />
</template>

<style>
.vue-repl {
    height: 700px !important;
}
</style>
```

**Comment by YangTingTing-tech** [comment] 2023-11-06 08:58
here is the wrong message in chrome console:
![image](https://github.com/vuejs/repl/assets/132062560/54b15323-418a-419d-9ea9-2078305740cd)

**Comment by alexsommers7** [comment] 2023-12-01 16:06
I had run into the same issue. It's a bit wonky, but I was able to solve it like so:

```js
const store = new ReplStore();

store.setImportMap({
    imports: {
        myLib: "myLib"
    }
});

const previewOptions = {
    headHTML: '<link rel="stylesheet" href="/myLib.css">',
    customCode: {
        importCode: `import myLib from 'myLib'`,
        useCode: `app.use(myLib)`
    }
};

const defaultFiles = store.getFiles();
delete defaultFiles["App.vue"];
store.setFiles({ ...defaultFiles, "myDefaultComponent.vue": myDefaultComponent}, "myDefaultComponent.vue");
```

**Comment by sxzz** [comment] 2023-12-31 10:49
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by sxzz** 2023-12-31 10:49 UTC
